### ISSUE TITLE
Use device language setting as default language

### ISSUE THREAD

**Issue by kpeatt** [CovidShield/mobile#111]
The app should use the device language setting as the default language.

Expected: Setting my phone to Français (Canada) puts COVID Shield into the French language.

Reality: Setting my phone to Français (Canada) keeps the app in English.

**Comment by sbearben** [comment]
Curious what the expected behaviour should be when language is switched in the app versus on device.

For example: User has french as device language -> in app switch to english: is app setting source of truth now? Same for the reverse situation - In app + device setting is english -> device language is switched to french: device setting is source of truth now?

**Comment by kpeatt** [comment]
I think the app always contains its own source of truth, the device setting just changes what the app defaults to on first start. So if you start with your device in French, the app defaults to French. If you change it to English, it will stay in that mode until you change it to something else.

**Comment by timarney** [comment]
Ref to downstream
https://github.com/cds-snc/covid-shield-mobile/issues/91

**Comment by henrytao-me** [comment]
PR should be up today.
